PRIVATE_TEST_HFILES = \
	cairo-analysis-surface-private.h \
	cairo-arc-private.h \
	cairo-cache-private.h \
	cairo-clip-private.h \
	cairo-freelist-private.h \
	cairo-ft-private.h \
	cairo-glitz-private.h \
	cairo-gstate-private.h \
	cairo-hash-private.h \
	cairo-meta-surface-private.h \
	cairo-mutex-list-private.h \
	cairo-mutex-private.h \
	cairo-os2-private.h \
	cairo-output-stream-private.h \
	cairo-paginated-surface-private.h \
	cairo-path-fixed-private.h \
	cairo-path-private.h \
	cairo-pdf-test.h \
	cairo-private.h \
	cairo-ps-test.h \
	cairo-quartz-private.h \
	cairo-scaled-font-subsets-private.h \
	cairo-scaled-font-test.h \
	cairo-skiplist-private.h \
	cairo-surface-fallback-private.h \
	cairo-svg-test.h \
	cairo-truetype-subset-private.h \
	cairo-type1-private.h \
	cairo-wideint-private.h \
	cairo-win32-private.h \
	cairo-xlib-private.h \
	cairo-xlib-test.h \
	cairoint.h
